export { default as Dashboard } from './Dashboard';
export { default as Exam } from './Exam';
export { default as Fail } from './Fail';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Recaps } from './Recaps';
export { default as Register } from './Register';
export { default as Schedule } from './Schedule';
export { default as Verify } from './Verify';